{application,appsignal_phoenix,
             [{applications,[kernel,stdlib,elixir,logger,appsignal_plug,
                             phoenix]},
              {description,"AppSignal's Phoenix instrumentation instruments calls to Phoenix applications to gain performance insights and error reporting"},
              {modules,['Elixir.Appsignal.Metadata.Phoenix.Socket',
                        'Elixir.Appsignal.Phoenix',
                        'Elixir.Appsignal.Phoenix.Application',
                        'Elixir.Appsignal.Phoenix.Channel',
                        'Elixir.Appsignal.Phoenix.EventHandler',
                        'Elixir.Appsignal.Phoenix.Instrumenter',
                        'Elixir.Appsignal.Phoenix.LiveView',
                        'Elixir.Appsignal.Phoenix.Template',
                        'Elixir.Appsignal.Phoenix.Template.EExEngine',
                        'Elixir.Appsignal.Phoenix.Template.ExsEngine',
                        'Elixir.Appsignal.Phoenix.View']},
              {registered,[]},
              {vsn,"2.0.12"},
              {mod,{'Elixir.Appsignal.Phoenix.Application',[]}}]}.
